---
name: 'Loop Shell GitHub Action'
description: 'A simple GitHub Action to execute a shell command in a loop with an items list'
author: 'Cliffano Subagio'
inputs:
  items:
    description: 'Items - space delimited string'
    type: string
    required: true
  command:
    description: 'Command to be executed - item accessed via $ITEM'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Execute command
      shell: bash
      run: |
        for ITEM in ${{ inputs.items }}; do
          eval ${{ inputs.command }}
        done
