---
name: 'Loop Shell GitHub Action'
description: 'A simple GitHub Action for running a shell command in a loop'
author: 'Cliffano Subagio'
inputs:
  items:
    description: 'List of items defined in a comma or space delimited string'
    type: string
    required: true
  command:
    description: 'Shell command to be executed in a loop, each run accesses an item on the list via $ITEM'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Execute command
      shell: bash
      run: |
        for ITEM in $(echo "${{ inputs.items }}" | tr ", " "\n"); do
          echo "Run command: ${{ inputs.command }}"
          eval ${{ inputs.command }}
        done
