---
name: 'Loop Shell GitHub Action'
description: 'A simple GitHub Action for running a shell command in a loop'
author: 'Cliffano Subagio'
inputs:
  items:
    description: 'List of items defined in a comma or space delimited string'
    type: string
    required: true
  command:
    description: 'Shell command to be executed in a loop, each run accesses an item on the list via $ITEM'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Execute command
      shell: python
      run: |
        import sys
        import subprocess
        from string import Template

        items_list = '${{ inputs.items }}'.split(', ')
        for item in items_list:
            command_template = Template('${{ inputs.command }}')
            command_merged = command_template.substitute(ITEM=item)
            print(f'Run: {command_merged}')
            result = subprocess.run(command_merged, shell=True)
            if result.returncode != 0:
                print(f'Error: {result.returncode}')
                sys.exit(result.returncode)
