name: 'Matrix-Shell GitHub Action'
description: 'Send test coverage data to Coveralls.io for analysis, change tracking, and notifications.'
author: 'Cliffano Subagio'
inputs:
  matrix:
    description: 'GitHub Action matrix in JSON format'
    required: true
  command:
    description: 'Command to be executed with the matrix'
    required: true
branding:
  color: 'blue'
  icon: 'command'
strategy:
  matrix: ${{ fromJSON(inputs.matrix) }}
runs:
  using: 'composite'
  steps:
    - name: Execute command
      run: ${{ inputs.command }}
      shell: bash
