---
name: 'Command Loop GitHub Action'
description: |
  A simple GitHub Action for running a shell command in a loop
  against a list of items
author: 'Cliffano Subagio'
branding:
  icon: 'repeat'
  color: 'white'
inputs:
  items:
    description: List of items defined in a comma and/or space-separated string
    type: string
    required: true
  command:
    description: |
      Command to be executed in a loop,
      each run can access an item from the list via $ITEM
    type: string
    required: true
  delimiters:
    description: |
      Items string delimiters, separated by pipe character,
      default: ", |,| " (comma followed by space, comma, space)
    type: string
    required: false
    default: ', | |,'
runs:
  using: 'composite'
  steps:
    - name: Execute shell command
      shell: python
      run: |
        import re
        import sys
        import subprocess
        from string import Template

        items_list = re.split('${{ inputs.delimiters }}', '${{ inputs.items }}')
        for item in items_list:
            command_template = Template('${{ inputs.command }}')
            command_merged = command_template.substitute(ITEM=item)
            print(f'Run: {command_merged}')
            result = subprocess.run(command_merged, shell=True)
            if result.returncode != 0:
                print(f'Error: {result.returncode}')
                sys.exit(result.returncode)
