---
name: CI
on: [push, pull_request]
env:
  NUMBERS: '1, 2, 3, 4, 5, 6, 7, 8, 9, 10'
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
      matrix:
        # Available Python versions:
        # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python: ['3.10', '3.12', '3.13']
    name: python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v4
        with:
          set-safe-directory: ${{ github.workspace }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: cliffano/command-docker-action@v1.0.0
        with:
          command: 'make ci'
          image: cliffano/studio
          shell: bash
      - name: 'Count from 1 to 10 with space-separated items'
        uses: cliffano/command-loop-action@main
        with:
          items: '1 2 3 4 5 6 7 8 9 10'
          command: 'echo "Count $ITEM"'
      - name: 'Count from 1 to 10 with space-separated items'
        uses: cliffano/command-loop-action@main
        with:
          items: '1,2,3,4,5,6,7,8,9,10'
          command: 'echo "Count $ITEM"'
      - name: 'Count from 1 to 10 with items from an environment variable'
        uses: cliffano/command-loop-action@main
        with:
          items: ${{ env.NUMBERS }}
          command: 'echo "Count $ITEM"'
      - name: 'Count from 1 to 10 with colon-separated items'
        uses: cliffano/command-loop-action@main
        with:
          items: '1:2:3:4:5:6:7:8:9:10'
          command: 'echo "Count $ITEM"'
          delimiters: ':'
